//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int AnswerID { get; set; }
        public string Content { get; set; }
        public bool Correct { get; set; }
        public int QuestionID { get; set; }
    
        public virtual ICollection<TestResult> TestResults { get; set; }
        public virtual Question Question { get; set; }
    }
}
