//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExationisEntities : DbContext
    {
        public ExationisEntities()
            : base("name=ExationisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TestResult> TestResults { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<TestPoint> TestPoints { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Access> Accesses { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
    }
}
