//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Users = new HashSet<User>();
        }
    
        public int LanguageID { get; set; }
        public string Name { get; set; }
        public string ISO { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
