//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.Questions = new HashSet<Question>();
            this.TestPoints = new HashSet<TestPoint>();
        }
    
        public int TestID { get; set; }
        public string Name { get; set; }
        public string Limitation { get; set; }
        public double Evaluation { get; set; }
        public int DisciplineID { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<TestPoint> TestPoints { get; set; }
    }
}
